

services:
  # Ваше приложение
  orderprod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Порт для вашего приложения
    container_name: notes-web-api
    depends_on:
      - postgresdb  # Зависимость от PostgreSQL

  # База данных PostgreSQL
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: db_postgresql_container

# Том для хранения данных PostgreSQL
volumes:
  postgres_data: